inherit_from: .rubocop_todo.yml

AllCops:
  # Rubocop doesn't support 2.0, so we'll use the minimum available
  TargetRubyVersion: 2.3
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'example/**/*'
    - 'lib/rudder-sdk-ruby.rb'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'bin/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - lib/rudderanalytics-ruby # Gem name, added for easier Gemfile usage

Naming/PredicateName:
  AllowedMethods:
    - is_requesting? # Can't be renamed, backwards compatibility

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BracesAroundHashParameters:
  Enabled: false

Style/DateTime:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

# Allow one-liner functions to be wrapped in conditionals rather
# than forcing a guard clause
Style/GuardClause:
  MinBodyLength: 2

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - 'spec/**/*'

Style/ModuleFunction:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose
