name: Test - Build - Publish

on: [push]

jobs:
  rake-spec:
    name: rake-spec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Run specs
        run: |
          bundle install
          rake spec

      - name: Build and Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: 5ad4663ccfe18408fa15e65bcddf86a4
